# Generated by Django 5.1.4 on 2025-01-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default=1, max_length=10, verbose_name='Принадлежность получателя'),
            preserve_default=False,
        ),
    ]
