# Generated by Django 5.1.4 on 2025-01-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_mailing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journallogs',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
