# Generated by Django 4.2.9 on 2025-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_journallogs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journallogs',
            name='logs',
        ),
        migrations.AddField(
            model_name='journallogs',
            name='message_error',
            field=models.TextField(default=1, verbose_name='Сообщение об ошибке'),
            preserve_default=False,
        ),
    ]
