# Generated by Django 4.2.9 on 2025-01-20 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_remove_journallogs_logs_journallogs_message_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journallogs',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='journallogs',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='type',
        ),
        migrations.AddField(
            model_name='journallogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journallogs',
            name='is_error',
            field=models.BooleanField(default=1, verbose_name='Является ошибкой'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default=1, max_length=10, verbose_name='Тип сообщения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='shipping',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='delay',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность'),
            preserve_default=False,
        ),
    ]
